// StatsExtractor/WebService/Frontend/NatStats/src/lib/MapApp/MapInfo/PolygonHistogramData.svelte
<!---
   Copyright (C) 2024  Argyros Argyridis arargyridis at gmail dot com
   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
--->

<script>
    import {
        currentProduct,
        dateEnd,
        dateStart,
    } from "../../../store/ProductParameters";
    import requests from "../../base/requests";
    import Highcharts from "highcharts";
    import "highcharts/highcharts-more";
    import { onMount } from "svelte";

    export let chartId = "histogram";
    export let mode = "raw";
    export let shown = true;
    export let polygonId = false;
    export let loading = true;

    let variable = $currentProduct.currentVariable;
    let noData = [[], []];
    export let diagramData = structuredClone(noData);
    let chart = null;

    export function getNoData() {
        return noData;
    }

    function refreshData() {
        if (!polygonId) return;

        reset();

        requests
            .fetchHistogramByPolygonAndDate(
                polygonId,
                $currentProduct.currentVariable.rtFlag.currentDate,
                $currentProduct.currentVariable.id,
                $currentProduct.currentVariable.rtFlag.id,
            )
            .then((response) => {
                let xAxisCategories = [];
                for (
                    let i = 0;
                    i < response.data.data.histogram.y.length;
                    i++
                ) {
                    xAxisCategories.push(
                        response.data.data.histogram.x[i].toString() +
                            "-" +
                            response.data.data.histogram.x[i + 1].toString(),
                    );
                }
                diagramData = [response.data.data.histogram.y, xAxisCategories];
                update();
                loading = false;
            });
    }

    function reset() {
        diagramData = structuredClone(noData);
        update();
        loading = true;
    }

    function setChartOptions() {
        return {
            credits: {
                enabled: false,
            },
            title: {
                text: "Region Frequency Histogram (raw)",
                style: {
                    fontSize: "15px",
                },
            },
            subtitle: {
                text: $currentProduct.currentVariable.rtFlag.currentDate.toDateString(),
            },
            plotOptions: {
                column: {
                    pointPadding: 0,
                    borderWidth: 1,
                    groupPadding: 0,
                    shadow: false,
                },
            },
            series: [
                {
                    name: "Histogram",
                    type: "column",
                    data: diagramData[0],
                },
            ],
            yAxis: {
                title: {
                    enabled: true,
                    text: "Number of Pixels",
                },
            },
            xAxis: {
                categories: diagramData[1],
                title: {
                    enabled: true,
                    text: "Frequency",
                },
            },
            legend: {
                enabled: false,
            },
        };
    }

    export function title() {
        return "Region Frequency Histogram (raw)";
    }

    export function toShow() {
        if ($currentProduct == null)
            return;
        
        let ret = false;
        if (mode == "raw") ret = $currentProduct.currentVariable != null;
        else if (mode == "anomalies")
            ret =
                $currentProduct.currentVariable.currentAnomaly.variable != null;
        return ret;
    }

    export function update() {
        let options = setChartOptions();
        chart = new Highcharts.Chart(chartId, options);
    }

    onMount(() => {
        update();
    });

    $: polygonId, refreshData();
</script>

<div id={chartId} class:d-none={!shown} />

// StatsExtractor/WebService/Frontend/stats-widget/src/components/charts/PolygonHistogramData.vue
<template>
		<highcharts ref="diagram"  :options="diagramOptions"/>
</template>


<script>
import requests from "../../libs/js/requests.js";
import {Chart} from 'highcharts-vue';
import Highcharts from 'highcharts'
import column from 'highcharts/modules/exporting';
column(Highcharts);

export default {
	name: "PolygonHistogramData",
	props:{},	
	components: {
		highcharts: Chart
	},
	computed: {
		diagramData: {
			get() {
				if (this.dgDt == null)
					return this.noData;
				return this.dgDt;
			},
			set(dt) {
				this.dgDt = dt;
			}
		},
		diagramOptions(){
			//this.updateChartData();
			return this.__computeChartOptions();
		},
		diagramTitle() {
			if (this.$store.getters.product == null || this.$store.getters.currentDate == null)
				return "Dummy Title";
			
			let tmpDate = new Date(Date.parse(this.$store.getters.currentDate));
			return "Region Histogram for raw Product (" + tmpDate.toDateString() + ")";
		},
		noData() {
			return [null, null];
		}
	},
	data() {
		return {	
			isLoading: true,
			dgDt: this.noData,
			polygonId: null,
			product:{id: null},
			date: null
		}
	},
	methods: {
		loads() {
			return this.isLoading;
		},
		updateChartData() {
			
			if (this.$store.getters.product == null || this.$store.getters.currentDate == null || this.$store.getters.selectedPolygon ==null)
				return;
			
			if (this.product.id == this.$store.getters.product.id && this.polygonId == this.$store.getters.selectedPolygon && this.date == this.$store.getters.currentDate)
				return;

			this.isLoading = true;
			this.product = this.$store.getters.product;
			this.date = this.$store.getters.currentDate;
			this.polygonId = this.$store.getters.selectedPolygon;
			requests.fetchHistogramByPolygonAndDate(this.polygonId, this.date, this.product.currentVariable.id).then((response) =>{
				this.resizeChart();
				let xAxisCategories = [];
				for (let i = 0; i < response.data.data.histogram.y.length; i++) {
					xAxisCategories.push(response.data.data.histogram.x[i].toString() +"-" + response.data.data.histogram.x[i+1].toString());
				}
				this.diagramData = [response.data.data.histogram.y, xAxisCategories];
				this.isLoading = false;
			}).catch( ()=> {
				this.diagramData = this.noData;
			});
		},
		reset() {
			this.diagramData = this.noData;
		},
		resizeChart() {
			if (this.diagramTitle != "Dummy Title")
				this.$refs.diagram.chart.reflow();
		},
		__computeChartOptions() {
			return {
				credits:{
					enabled:false
				},
				title:{
					text: this.diagramTitle,
					style: {
						fontSize: '15px' 
					}
				},
				plotOptions: {
					column: {
						pointPadding: 0,
						borderWidth: 1,
						groupPadding: 0,
						shadow: false
					}
				},
				series: [{
					name: "Histogram",
					type: "column",
					data: this.diagramData[0]
				}],
				yAxis:{
					title:{
						enabled:true,
						text:"Number of Pixels"
					}
				},
				xAxis:{
					categories: this.diagramData[1],
					title:{
						enabled:true,
						text:"Frequency",
					}
				},
				legend:{
					enabled: false
				}
			}
		}
	}
}
</script>


<style scoped>
</style>
