// StatsExtractor/WebService/Frontend/NatStats/src/components/MapApp.vue
<!---
   Copyright (C) 2022  Argyros Argyridis arargyridis at gmail dot com
   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
--->
<template>
	<OLMap id="map1" v-bind:center=[0,0] v-bind:zoom=2 v-bind:bingKey=bingKey v-bind:epsg=projectEPSG  ref="map1" class="map"
		v-on:featureClicked="updateSelectedPolygon($event)"
		v-on:mapCoordinate="moveMarker($event)"
	/>
</template>

<script>
import OLMap from './libs/OLMap.vue';
import requests from '../libs/js/requests.js';
import options from "../libs/js/options.js";
import utils from "../libs/js/utils.js";
import {areaDensityOptions, consolidationPeriods} from "../libs/js/constructors.js";
import VectorLayer from 'ol/layer/Vector';


import {Fill, Stroke, Style, Icon } from 'ol/style';

export default {
	name: 'MapApp',
	computed: {
		product(){
			return this.$store.getters.product;
		},
		stratification(){
			return this.$store.getters.currentStratification;
		}
	},
	data() {
		return {
			activeWMSLayer: null,
			bingId: null,
			clickedPointLayerId: null,
			pointerLayerId: null,
			bingKey: options.bingKey,
			initCmp: true,
			projectEPSG: "EPSG:3857",
			productVariableZIndex: 1,
			stratificationZIndex: 3,
			anomaliesZIndex: 2,
			markerZIndex: 4,
			stratificationColorData: {},
			stratificationViewProps: {
				stratID: null,
				variableID: null,
				rtFlag: {id: null},
				date: null,
				statisticsViewMode: null,
				stratifiedOrRaw: null,
				currentStyles:{},
				styleWMS: new Style({
					fill: new Fill({color: "rgb(54, 102, 142, 0.0)"}),
					stroke: new Stroke({
						color:  "rgb(54, 102, 142, 0.6)",
						width: 1.5,
					})
				}),
				defaultVectorStyle: null
			}
		}
	},	
	props: {},
	components: {
		OLMap
	},
	methods: {
		init() {
			//cartographic background
			this.bingId = this.$refs.map1.addBingLayerToMap("aerial", true, 0);
			this.$refs.map1.setVisibility(this.bingId, true);
			
			requests.categories().then((response) => {
				this.$store.commit("setCategoryInfo", response.data.data);
				this.fetchProductInfo();
				this.toggleClickOnMap();
			});

			this.defaultVectorStyle = new VectorLayer().getStyleFunction()();
		},
		activateLayer(key) {
			if (this.activeWMSLayer != null)
				this.$refs.map1.setVisibility(this.wmsLayers[this.activeWMSLayer].layerId, false);
				
			this.$refs.map1.setVisibility( this.wmsLayers[key].layerId, true);
			this.activeWMSLayer = key;
		},
		clearStratifications() {
			if (this.product == null || this.$store.getters.stratifications == null)
				return;
		},
		clearPolygonSelection() {
			this.$refs.map1.clearCurrentPolygonSelection();
			this.$store.commit("selectedPolygon", null);
		},
		clearWMSLayers() {
			if (this.product == null || this.$store.getters.allCategories == null)
				return;

			//remove wms layers from map
			this.$store.getters.allCategories.forEach( (category) => {
				if(category.products != null) {
					category.products.info.forEach( (product) => {
						product.variables.forEach((variable) =>{						
							//removing raw variable wms
							Object.keys(variable.cog.layers).forEach( (key) => {
								this.$refs.map1.removeLayer(variable.cog.layers[key].layerId);
							});
							
							//removing anomalies wms
							if(variable.anomaly_info != null)
								variable.anomaly_info.forEach( (anomaly) => {
									Object.keys(anomaly.cog.layers).forEach( (key) => {
										this.$refs.map1.removeLayer(anomaly.cog.layers[key].layerId);
									});
								});
						});
					});
				}
			});
		},
		emit(eventName, data) {
			this.$emit(eventName, data);
		},
		moveMarker(evt) {
			if(this.clickedPointLayerId == null)
				this.clickedPointLayerId = this.$refs.map1.createEmptyVectorLayer(this.markerZIndex);
			
			if (evt ==null) {
				this.$refs.map1.clearVectorLayer(this.clickedPointLayerId);
				return;
			}
			
			this.$refs.map1.setVisibility(this.clickedPointLayerId, true);
			this.$refs.map1.clearVectorLayer(this.clickedPointLayerId);
			let iconProps = utils.markerProperties();
			this.$refs.map1.addPointToLayer(this.clickedPointLayerId, 2, evt.coordinate[0], evt.coordinate[1],  {icon:	new Icon(iconProps)} );
		},
		refreshCurrentStratificationStyle(){
			this.$refs.map1.getLayerObject(this.$store.getters.currentStratification.layerId).changed();
		},		
		refreshStratifications() {
			let stratifications = this.$store.getters.stratifications;
			if (stratifications == null)
				return;

			Object.keys(stratifications.info).forEach((strat) => {
				//need to be in-store mutation!!!
				stratifications.info[strat].layerId = this.$refs.map1.createVectorTileLayer({
					url: stratifications.info[strat].url,
					maxZoom:stratifications.info[strat].maxZoom,
					zIndex: this.stratificationZIndex
				});
				this.$refs.map1.setVisibility(stratifications.info[strat].layerId, false);
			});
		},
		fetchProductInfo() {
			if(this.$store.getters.activeCategory.products != null)
				return;
				
			requests.fetchProductInfo(this.$store.getters.dateStart, this.$store.getters.dateEnd, this.$store.getters.activeCategory.id).then((response)=>{
				this.$store.commit("setCategoryProducts", response.data.data);
				this.updateWMSLayers();
				requests.fetchStratificationInfo().then((response)=>{
					this.$store.commit("setStratifications", response.data.data);
					if(this.initCmp) {
						this.initCmp = false;
						this.refreshStratifications();
						this.updateStratificationLayerVisibility();
						this.updateStratificationLayerStyle();
					}
				});
			});
		},
		setLayerVisibility(id, val) {
			if(id != null)
				this.$refs.map1.setVisibility(id, val);
		},
		updateWMSLayers(displayFirst = false) {
			//no product available or the wms layers have been already fetched
			if (this.product == null || this.$store.getters.productWMSLayer != null) 
				return;
			
			requests.productCog(this.product.id, this.product.currentVariable.id, this.$store.getters.dateStart, this.$store.getters.dateEnd).then(data =>{
				if (data.data.data == null)
					return;
				let dt = {}
				Object.keys(data.data.data).forEach(rt =>{
					dt[rt] = {};
					Object.keys(data.data.data[rt]).forEach(date => {
						dt[rt][date] = {
							layerId: null, 
							url: options.s3CogURL + data.data.data[rt][date]
						}
					});
				});
				this.$store.commit("setCurrentVariableCogLayers", dt);
				if(displayFirst)
					this.updateWMSVisibility();
			});
			
			if (this.$store.getters.currentAnomaly == null)
				return;
			
			console.log(this.$store.getters.currentAnomaly);
			
			requests.productCog(this.$store.getters.currentAnomaly.id, this.product.currentVariable.id, this.$store.getters.dateStart, this.$store.getters.dateEnd).then(data =>{
				if (data.data.data == null)
					return;
				let dt = {}
				Object.keys(data.data.data).forEach(rt =>{
					dt[rt] = {};
					Object.keys(data.data.data[rt]).forEach(date => {
						dt[rt][date] = {
							layerId: null, 
							url: options.s3CogURL + data.data.data[rt][date]
						}
					});
				});
				this.$store.commit("setCurrentVariableCogLayers", dt);
				if(displayFirst)
					this.updateWMSVisibility();
			});
			
			
			

			//need to do the same with the anomalies!!!!
		},
		toggleClickOnMap() {
			this.$refs.map1.toggleGetMapCoordinates();
		},
		toggleLayerVisibility(id) {
			if(id != null)
				this.$refs.map1.toggleLayerVisibility(id);
		},
		toggleRawAnomaliesWMSView() {
			this.$refs.map1.setVisibility( this.$store.getters.productWMSLayer.layerId,  this.$store.getters.productStatisticsViewMode == 0);
			this.$refs.map1.setVisibility( this.$store.getters.currentAnomalyWMSLayer.layerId,  this.$store.getters.productStatisticsViewMode == 1);
		},
		updateProductWMSVisibility() {
			if (this.$store.getters.previousProductWMSLayer != null)
				this.$refs.map1.setVisibility(this.$store.getters.previousProductWMSLayer.layerId, false);
			this.$refs.map1.setVisibility( this.$store.getters.productWMSLayer.layerId, true);
		},
		updatecurrentAnomalyWMSVisibility() {
			if (this.$store.getters.previouscurrentAnomalyWMSLayer != null) {
				this.$refs.map1.setVisibility(this.$store.getters.previouscurrentAnomalyWMSLayer.layerId, false);
			}

			this.$refs.map1.setVisibility( this.$store.getters.currentAnomalyWMSLayer.layerId, true);
		},
		updateWMSVisibility() {
			if (this.$store.getters.previousCog != null && this.$store.getters.previousCog.layerId != null) 
				this.$refs.map1.setVisibility(this.$store.getters.previousCog.layerId, false);
			
			if(this.$store.getters.product != null && (this.$store.getters.productCogLayers == null || Object.keys(this.$store.getters.productCogLayers).length == 0) ) { //wms layers have not been initialized for current product, so do so
				this.updateWMSLayers(true);
			
			}
			else if (this.$store.getters.currentCogLayer != null) {
				if (this.$store.getters.currentCogLayer.layerId == null)
					this.$store.getters.currentCogLayer.layerId = this.$refs.map1.createGeoTIFFLayer(this.$store.getters.currentCogLayer.url, this.productVariableZIndex);
				
				this.$refs.map1.setVisibility(this.$store.getters.currentCogLayer.layerId, this.$store.getters.stratifiedOrRaw == 1);
			}
		},		
		updateSelectedPolygon(evt) {
			let id = null;
			if (evt != null)
				id = evt.getId();
			this.$store.commit("selectedPolygon", id);
		},		
		updateStratificationLayerStyle() {
			if  ( this.$store.getters.currentStratification == null || this.$store.getters.product == null || this.$store.getters.currentDate == null)
				return;
			
			//if no change, stop
			if (this.stratificationViewProps.stratID == this.$store.getters.currentStratification.id && this.stratificationViewProps.date == this.$store.getters.currentDate && 
			this.stratificationViewProps.variableID == this.$store.getters.product.currentVariable.id && this.$store.getters.productStatisticsViewMode == this.statisticsViewMode && this.$store.getters.stratifiedOrRaw == this.stratificationViewProps.stratifiedOrRaw && this.$store.getters.product.rtFlag.id == this.stratificationViewProps.rtFlag.id)
				return;
			
			this.stratificationViewProps.stratID 			= this.$store.getters.currentStratification.id;
			this.stratificationViewProps.date 			= this.$store.getters.currentDate;
			this.stratificationViewProps.variableID 		= this.$store.getters.product.currentVariable.id;
			this.stratificationViewProps.stratifiedOrRaw 	= this.$store.getters.stratifiedOrRaw;
			this.stratificationViewProps.rtFlag 			= this.$store.getters.product.rtFlag;

			if (this.$store.getters.productStatisticsViewMode == 1 && this.$store.getters.currentAnomaly != null) //seeing anomalies
				this.stratificationViewProps.variableID = this.$store.getters.currentAnomaly.id;
						
			if (this.stratificationViewProps.stratifiedOrRaw == 1) {
				let tmpLayer = this.$refs.map1.getLayerObject(this.$store.getters.currentStratification.layerId);
				tmpLayer.setStyle(this.stratificationViewProps.styleWMS);
				return;
			}
			

			if (! (this.stratificationViewProps.stratID in this.stratificationColorData))
				this.stratificationColorData[this.stratificationViewProps.stratID] = {};
			
			if (!(this.stratificationViewProps.rtFlag.id in  this.stratificationColorData[this.stratificationViewProps.stratID]))
				this.stratificationColorData[this.stratificationViewProps.stratID][this.stratificationViewProps.rtFlag.id] = {}
			
			if (! (this.stratificationViewProps.variableID in this.stratificationColorData[this.stratificationViewProps.stratID][this.stratificationViewProps.rtFlag.id]))
				this.stratificationColorData[this.stratificationViewProps.stratID][this.stratificationViewProps.rtFlag.id][this.stratificationViewProps.variableID] = {};

			if (!(this.stratificationViewProps.date in this.stratificationColorData[this.stratificationViewProps.stratID][this.stratificationViewProps.rtFlag.id][this.stratificationViewProps.variableID])) {
				this.$refs.map1.activateSpinner();
				requests.fetchStratificationDataByProductAndDate(this.stratificationViewProps.date, this.stratificationViewProps.variableID, this.stratificationViewProps.rtFlag.id, this.stratificationViewProps.stratID).then((response)=>{
					this.$refs.map1.activateSpinner();
					let styles = {};
					this.stratificationColorData[this.stratificationViewProps.stratID][this.stratificationViewProps.rtFlag.id][this.stratificationViewProps.variableID][this.stratificationViewProps.date] = styles;

					let areaDensityInfo = new areaDensityOptions();
					areaDensityInfo.forEach(density => {
						styles[density.color_col] = {};
					});
					styles["meanval_color"] = {}
					if (response.data.data == null)
						return;
					for (let idx = 0; idx < response.data.data.length; idx++) {
						let rec = response.data.data[idx];
						let id = rec.id;
						Object.keys(styles).forEach(colorCol => {
							let color = rec[colorCol];							
							if (color != null) {
								let joinedColor = color.join();
								styles[colorCol][id] = new Style({
									fill: new Fill({
										color: "rgba(" + joinedColor + ",0.7)",
									}),
									stroke: new Stroke({
										color:  "rgba(" + joinedColor + ",1.0)",
									width: 1.2,
									})
								});
							}
							else
								styles[colorCol][id] = new Style();
						});
					}
					this.setStratificationStyle();
				});
			} 
			else 
				this.setStratificationStyle();
		},
		setStratificationStyle() {
			this.$refs.map1.activateSpinner();
			let tmpLayer = this.$refs.map1.getLayerObject(this.$store.getters.currentStratification.layerId);
			let colorCol = this.$store.getters.stratificationViewOptions.colorCol;
			tmpLayer.setStyle( (ft) => {
				let retStyle = this.stratificationColorData[this.stratificationViewProps.stratID][this.stratificationViewProps.rtFlag.id][this.stratificationViewProps.variableID][this.stratificationViewProps.date][colorCol][ft.getId()];

				if (retStyle == null)
					return this.defaultVectorStyle;

				return retStyle;
			});
			this.$refs.map1.deactivateSpinner();
		},
		updateStratificationLayerVisibility() {
			if (this.$store.getters.previousStratification != null)
				this.$refs.map1.setVisibility( this.$store.getters.previousStratification.layerId, false);

			if (this.$store.getters.currentStratification != null) {
				this.$refs.map1.setVisibility( this.$store.getters.currentStratification.layerId, true);
				this.$refs.map1.highlightOnLayer(this.$store.getters.currentStratification.layerId);
			}
		}
	},
	mounted(){
		this.init();
	}
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>

.map {
	width: 100%;
	height: 100vh;
	position: absolute;
}

	.logo {
		justify-content:end;
		position: fixed;
		bottom: 0px;
		right: 0px;
		height:8%;
	}
</style>

// StatsExtractor/WebService/Frontend/NatStats/src/lib/MapApp/MapApp.svelte
<!---
   Copyright (C) 2023  Argyros Argyridis arargyridis at gmail dot com
   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <http://www.gnu.org/licenses/>.
--->

<script>
    import OLMap from "../base/OLMap.svelte";
    import { onMount } from "svelte";
    import { currentBoundary, boundaries } from "../../store/Boundaries.js";
    import {
        currentProduct,
        styleCache,
    } from "../../store/ProductParameters.js";
    import {
        analysisModes,
        DisplayPolygonValues,
        stratifiedOrRawModes,
    } from "../base/CGLSDataConstructors.js";
    import { Fill, Stroke, Style, Icon } from "ol/style";
    import requests from "../base/requests.js";
    import options from "../base/options.js";
    import MapInfo from "./MapInfo/MapInfo.svelte";
    import utils from "../base/utils.js";

    let refs = {};
    let visibleBoundary = null;
    let visibleCogLayerId = null;
    let selectedFeatureId = null;
    let clickedCoordinates = null;
    let mapInfoLoading = false;
    let markerLayer = null;

    let defaultBoundariesStyle = new Style({
        fill: new Fill({ color: "rgb(208, 208, 208, 0.3)" }),
        stroke: new Stroke({
            color: "rgb(0, 170, 255, 0.3)",
            width: 1.5,
        }),
    });

    let outlineboundariestyle = new Style({
        fill: new Fill({ color: "rgb(54, 102, 142, 0.0)" }),
        stroke: new Stroke({
            color: "rgb(54, 102, 142, 0.6)",
            width: 1.5,
        }),
    });

    //Boundary_id/variable_id/rt_flag/raw_or_anomaly/date/column_name/style_array

    function changeVisibleBoundary() {
        if (!("map" in refs)) return;

        if ($currentBoundary.url == null) return;

        if (visibleBoundary != null)
            refs.map.setVisibility($boundaries[visibleBoundary].layerId, false);

        visibleBoundary = $currentBoundary.id;
        refs.map.setVisibility($boundaries[visibleBoundary].layerId, true);
    }

    function refreshBoundaries() {
        let keys = Object.keys($boundaries);
        keys.sort();
        keys.forEach((key) => {
            $boundaries[key]["zIndex"] = options.vectorTileZIndex;
            $boundaries[key].layerId = refs.map.createVectorTileLayer(
                $boundaries[key],
            );
            refs.map.highlightOnLayer($boundaries[key].layerId);
        });

        visibleBoundary = keys[0];
        //refs.map.highlightOnLayer($boundaries[keys[0]].layerId);
        refs.map.setVisibility($boundaries[keys[0]].layerId, true);
    }

    function refreshMarker() {
        if (!("map" in refs)) return;

        refs.map.clearVectorLayer(markerLayer);
        console.log();
        refs.map.addPointToLayer(
            markerLayer,
            1,
            clickedCoordinates.obj.coordinate[0],
            clickedCoordinates.obj.coordinate[1],
            { icon: new Icon(utils.markerProperties()) },
        );
    }

    function setBoundaryStyle(tmpLayer, style) {
        tmpLayer.setStyle((ft) => {
            return style[ft.getId()];
        });
    }

    function setViewOptions() {
        if (visibleBoundary == null) return;

        let product = $currentProduct;
        let analysisMode =
            $currentProduct.currentVariable.mapViewOptions.analysisMode;
        let dataView = $currentProduct.currentVariable.mapViewOptions.dataView;
        let variable = $currentProduct.currentVariable;
        if (analysisMode == analysisModes[1])
            variable = $currentProduct.currentVariable.currentAnomaly.variable;

        let varId = variable.id;
        let rt = $currentProduct.currentVariable.rtFlag.id;
        let tmpLayer = refs.map.getLayerObject(
            $boundaries[visibleBoundary].layerId,
        );
        let date = $currentProduct.currentVariable.rtFlag.currentDate
            .toISOString()
            .substr(0, 19);
        let strata = $currentBoundary;

        if (
            Object.keys(variable.cog.layers).length > 0 &&
            rt in variable.cog.layers &&
            date in variable.cog.layers[rt]
        )
            //cog layers have been fetched
            variable.cog.current = variable.cog.layers[rt][date];
        
        if (visibleCogLayerId != null)
            refs.map.setVisibility(visibleCogLayerId, false);

        if (dataView == stratifiedOrRawModes[0]) {
            //checking if color in cache
            refs.map.activateSpinner();
            //console.log("spinner activated!");

            //Boundary_id/product_id/rt_flag/raw_or_anomaly/date/column_name/style_array
            if (!(strata.id in $styleCache)) $styleCache[strata.id] = {};

            let strataCache = $styleCache[strata.id];
            if (!(product.currentVariable.id in strataCache))
                strataCache[product.currentVariable.id] = {};

            let variableCache = strataCache[product.currentVariable.id];
            if (!(rt in variableCache)) variableCache[rt] = {};

            let rtCache = variableCache[rt];
            if (
                !(
                    product.currentVariable.mapViewOptions.analysisMode in
                    rtCache
                )
            )
                rtCache[product.currentVariable.mapViewOptions.analysisMode] =
                    {};

            let analysisCache =
                rtCache[product.currentVariable.mapViewOptions.analysisMode];

            if (!(date in analysisCache)) analysisCache[date] = {};

            let dateCache = analysisCache[date];
            let columnName =
                product.currentVariable.mapViewOptions.displayPolygonValue
                    .colorCol;
            if (
                product.currentVariable.mapViewOptions.analysisMode ==
                analysisModes[1]
            ) {
                columnName =
                    product.currentVariable.currentAnomaly.variable
                        .mapViewOptions.displayPolygonValue.colorCol;
                varId = product.currentVariable.currentAnomaly.variable.id;
            }

            if (!(columnName in dateCache)) {
                let polygonStyles = DisplayPolygonValues(
                    $currentProduct.currentVariable.valueRanges,
                );
                polygonStyles.forEach((polyStyle) => {
                    dateCache[polyStyle.colorCol] = {};
                });

                requests
                    .fetchBoundaryDataByProductAndDate(
                        date,
                        varId,
                        rt,
                        strata.id,
                    )
                    .then((response) => {
                        if (response.data.data == null) {
                            tmpLayer.setStyle(defaultBoundariesStyle);
                            refs.map.deactivateSpinner();
                            //console.log("spinner deactivated 1");
                            return;
                        }
                        Promise.all(
                            response.data.data.map((rec) =>
                                styleCreator(rec, dateCache),
                            ),
                        ).then((e) => {
                            setBoundaryStyle(tmpLayer, dateCache[columnName]);
                            refs.map.deactivateSpinner();
                            //console.log("spinner deactivated 2");
                        });
                    });
            } else {
                if (Object.keys(dateCache[columnName]).length == 0)
                    tmpLayer.setStyle(defaultBoundariesStyle);
                else setBoundaryStyle(tmpLayer, dateCache[columnName]);
                refs.map.deactivateSpinner();
                //console.log("spinner deactivated 3");
            }
        } else if (dataView == stratifiedOrRawModes[1]) {
            tmpLayer.setStyle(outlineboundariestyle);
            if (visibleCogLayerId != null)
                refs.map.setVisibility(visibleCogLayerId, false);

            if (!variable.cog.current.url) return;

            if (!variable.cog.current.layerId) {
                variable.cog.current.layerId = refs.map.createGeoTIFFLayer(
                    variable.cog.current.url,
                    options.cogZIndex,
                );
                console.log(variable.cog.current.layerId);
            }

            refs.map.setVisibility(variable.cog.current.layerId, true);
            visibleCogLayerId = variable.cog.current.layerId;
        }
    }

    function styleCreator(rec, dateCache) {
        Object.keys(dateCache).forEach((colorCol) => {
            let color = rec[colorCol];
            if (color != null) {
                let joinedColor = color.join();
                dateCache[colorCol][rec.id] = new Style({
                    fill: new Fill({
                        color: "rgba(" + joinedColor + ",0.7)",
                    }),
                    stroke: new Stroke({
                        color: "rgba(" + joinedColor + ",1.0)",
                        width: 1.2,
                    }),
                });
            } else dateCache[colorCol][rec.id] = defaultBoundariesStyle;
        });
    }

    function toggleSpinner() {
        if (!refs.map) return;

        if (mapInfoLoading) refs.map.activateSpinner();
        else refs.map.deactivateSpinner();
    }

    //reactivity
    $: if ($boundaries && "map" in refs) refreshBoundaries();
    $: $currentBoundary, changeVisibleBoundary();
    $: if (
        $currentBoundary &&
        $currentProduct  &&
        "map" in refs
    )
        setViewOptions();
    $: mapInfoLoading, toggleSpinner();
    $: clickedCoordinates, refreshMarker();

    onMount(() => {
        let layerId = refs.map.addBingLayerToMap("aerial", options.bingKey);
        refs.map.setVisibility(layerId, true);
        refs.map.toggleGetMapCoordinates();

        markerLayer = refs.map.createEmptyVectorLayer(6);
        refs.map.setVisibility(markerLayer, true);
    });
</script>

<div class="col px-0 mainMap">
    
    <MapInfo
        mapInfoId="mapInfoId"
        {selectedFeatureId}
        {clickedCoordinates}
        bind:dataLoading={mapInfoLoading}
    />

    <OLMap
        id="basemap"
        class="map"
        bind:this={refs.map}
        disableMapControls={true}
        bind:selectedFeatureId
        bind:clickedCoordinates
    />
</div>

<style>
    .mainMap :global(.map) {
        height: 100vh;
        position: relative;
    }
</style>
